// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: "postgresql://neondb_owner:npg_oPOpqvfy8a9h@ep-lively-term-abwi3v6b.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require",
    directUrl:
      "postgresql://neondb_owner:npg_oPOpqvfy8a9h@ep-lively-term-abwi3v6b.eu-west-2.aws.neon.tech/neondb?sslmode=require",
  },
});
